apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q4o1j30nn-python 
  janus-idp.io/tekton: q4o1j30nn-python
  backstage.io/kubernetes-id: q4o1j30nn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q4o1j30nn-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml